### PR TITLE
Add `Controller` type for interacting with `Receiver`

### PR DESCRIPTION
**Pull request by tobz**
This new type provides access to the `Receiver` for not only dealing with dynamic interests, but also getting snapshots of the meters from the `Receiver`.

While the HTTP server baked into the `Receiver` may suffice, this allows external implementations to tap into the same data stream providing their own reporting, and frees the `Receiver` from concerns of reporting entirely.

### CODE REVIEW

**Comment by tobz** [comment]
Also, this PR switches to using `mio-extras` for the mio channels, as recommended by the deprecation warnings from mio itself.

**Comment by tobz** [comment]
Yeah, it's not from carllerche which is sort of feelsbadman but given that it's clearly blessed by him... whatever!

I still need to pull performance numbers but presumably this should be a no-op, slightly faster at best.  

Anything immediate that jumps out at you as a problem?

**Comment by brayniac** [comment]
Overall - this is looking good. It is benchmarking nicely on my test box. Seeing a slight performance boost =)

Two fixes needed to make cargo test pass: `examples/allen.rs` and doc comments in the main `lib.rs` look for `http_listen` believe we can just remove the listener for those.

**Comment by tobz** [comment]
This should finally be good to go. :)

**Review by brayniac — APPROVED** [review]

**Comment by brayniac** [comment]
Published to crates.io as 0.6.0. Thanks for your contribution!

**Pull request merged**
